### ISSUE TITLE
'integer out of range' error

### ISSUE THREAD

**Issue by jbragg** [toomim/utility#1]
caused by models/**init**.py line 410:

timeout=os.sys.maxint

**Comment by toomim** [comment]
Oh really! That jerk. I haven't seen that, or know what line is actually causing it. (It can't be the "=" assignment operator itself, can it?)

I suggest changing this to something like 99999. It doesn't need to be maxint. Just needs be a large number of seconds. As long as it's greater than an hour or two it should be ok.

I've had an argument on the web2py mailing list about this timeout field, actually.

**Comment by jbragg** [comment]
If I comment out that line, the error disappears.

Why not hardcode a particular number of seconds, given that on at least one system (mine), this error occurs?

**Comment by toomim** [comment]
You can't comment out the line. The default is 60 seconds, which is not enough. The scheduler tasks will fail and people won't get paid and hits won't get launched.

Hardcoding it is what I suggested, when I said change it to something like 99999. Maxint is a hardcoded number of seconds itself.

I would be curious though, personally, and look into exactly what line it's failing on. Is there a reason you didn't look into that? Doesn't the error message come with a line number?

**Comment by jbragg** [comment]
I wasn't suggesting commenting out the line; I was suggesting changing it to something like 99999 on the master branch because maxint seems to cause problems.

I mentioned that commenting out the line causes the error to disappear as an indication that that particular line is causing the error (the error message didn't come with a line number). So, line 410 seems to be the troublemaker, and more generally it is the call to update_or_insert() when the db.scheduler_task table is empty.

**Comment by toomim** [comment]
Yes yes, please try changing it to 99999 in your code and if the problem goes away, push it to master.

I know that line 410 is the troublemaker. I was asking WHY. What line is throwing the actual error? Line 410 is not throwing the error. There is no range check there. You got a range error. But this is not critical, just a curiosity that might lead us to an insight so that we can solve this problem in a deeper way.

I'm not sure why this has been difficult to communicate. :P

**Comment by jbragg** [comment]
Right. I guess the exception doesn't give the filename + linenumber. Any idea how to get that information? The following method only provides **init**.py and line 410:

http://stackoverflow.com/questions/1278705/python-when-i-catch-an-exception-how-do-i-get-the-type-file-and-line-number#answer-1278740

**Comment by toomim** [comment]
Chat me

**Comment by toomim** [comment]
Ok, the problem is your python's ints are 64 bit and it's failing to store that in postgres's 32 bit integers. I recommend replacing that line with:

```
timeout = 24 * 60 * 60 * 2, # two days should be enough for everybody
```

This will be only 172800, which is far less than the 9223372036854775807 of your 64 bit max int.
